### ISSUE TITLE
Element type is invalid in functional component.

### ISSUE THREAD

**Issue by talentdevguru** [ahernandez9/react-native-arc-progress-bar#2]
Hello Sir, I am going to use this package in my app.
After integrated, Errors are appear.
Please let me know how can solve this.
Thanks

import React, { useCallback, useState } from 'react';
import { View } from 'react-native';

import { ArcProgressBar } from 'react-native-arc-progress-bar';

function Login(props) {
  const [changingValue, setChangingValue] = useState(0);
  const changingValueChanged = useCallback(
    value => setChangingValue(value),
    [],
  );

  const { navigation } = props;
  navigation.setOptions({ headerShown: false });

  const onChange = newValue => {
    changingValueChanged(newValue);
  };

  return (
    <View style={styles.container}>
      <ArcProgressBar
        rectangularSize={500}
        lowerValue={50}
        stackedValue={changingValue}
        higherValue={550}
        maxValue={1200}
        showCursor
        onChange={onChange}
      />
    </View>
  );
}

Login.propTypes = {
  navigation: PropTypes.object.isRequired,
};

export default Login;
----------------------------Error------------------------------------------------------------
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by ahernandez9** [comment]
Hello @talentdevguru .
It looks you are not using the component anywhere in your code, so I can say the error you are getting is not related to the component
